labels:
  background: 0
  buildings: 1
  helmet: 2
  worker: 3
  bgchar: 4
  equipment: 5

assets:
  - path: assets/models/equipment/wheelbarrow/wheelbarrow.obj
    category_id: 5
    scale: 0.01
  - path: assets/models/worker/worker2/worker2.obj
    category_id: 3
    scale: 1.0

lighting:
  energy: 300

camera:
  location: [0, -5, 0]
  rotation: [1.57, 0, 0]   # ~ np.pi/2, 0, 0
